# Generated by Django 5.2 on 2025-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
