# Generated by Django 5.2.1 on 2025-05-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_mobile_verified',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='temporaryuserdata',
            name='is_mobile_verified',
        ),
    ]
