# Generated by Django 5.2.1 on 2025-05-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteHistory',
            fields=[
                ('deleteID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseHistory',
            fields=[
                ('historyID', models.AutoField(primary_key=True, serialize=False)),
                ('plantID', models.IntegerField()),
                ('diseaseID', models.IntegerField()),
                ('date_detected', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('editID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackRating',
            fields=[
                ('feedbackID', models.AutoField(primary_key=True, serialize=False)),
                ('feedbackText', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
