# Generated by Django 5.2 on 2025-05-06 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseHistory',
            fields=[
                ('historyID', models.AutoField(primary_key=True, serialize=False)),
                ('plantID', models.IntegerField()),
                ('diseaseID', models.IntegerField()),
                ('date_detected', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeleteHistory',
            fields=[
                ('deleteID', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diseasehistory')),
            ],
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('editID', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diseasehistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackRating',
            fields=[
                ('feedbackID', models.AutoField(primary_key=True, serialize=False)),
                ('feedbackText', models.TextField()),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
