# Generated by Django 5.2.1 on 2025-05-20 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deletehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diseasehistory',
            name='diseaseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disease'),
        ),
        migrations.AddField(
            model_name='diseasehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletehistory',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diseasehistory'),
        ),
        migrations.AddField(
            model_name='edithistory',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diseasehistory'),
        ),
        migrations.AddField(
            model_name='edithistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diseasehistory',
            name='plantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plant'),
        ),
        migrations.AddField(
            model_name='disease',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='core.plant'),
        ),
    ]
