# Generated by Django 5.2 on 2025-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasehistory',
            name='date_detected',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
