# Generated by Django 5.2.1 on 2025-05-13 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plant_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasehistory',
            name='diseaseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disease'),
        ),
        migrations.AlterField(
            model_name='diseasehistory',
            name='plantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plant'),
        ),
    ]
