# Generated by Django 5.2.1 on 2025-05-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_diseasehistory_diseaseid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_samples/'),
        ),
    ]
